package com.example.data.service

import com.example.BuildConfig
import com.example.data.model.GroundingChunk
import com.example.data.model.SearchGroundedResult
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import okhttp3.MediaType.Companion.toMediaType
import okhttp3.OkHttpClient
import okhttp3.Request
import okhttp3.RequestBody.Companion.toRequestBody
import org.json.JSONArray
import org.json.JSONObject
import java.util.concurrent.TimeUnit

class GeminiSearchService {

    private val client = OkHttpClient.Builder()
        .connectTimeout(60, TimeUnit.SECONDS)
        .readTimeout(60, TimeUnit.SECONDS)
        .writeTimeout(60, TimeUnit.SECONDS)
        .build()

    suspend fun analyzeWithGoogleSearch(prompt: String): SearchGroundedResult = withContext(Dispatchers.IO) {
        val apiKey = try {
            BuildConfig.GEMINI_API_KEY
        } catch (_: Throwable) {
            ""
        }

        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return@withContext SearchGroundedResult(
                query = prompt,
                responseText = "To enable Google Search Grounding with Gemini 3.5 Flash, please configure your Gemini API Key in the AI Studio Secrets panel.",
                errorMessage = "API key not configured"
            )
        }

        val url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3.5-flash:generateContent?key=$apiKey"

        val requestJson = JSONObject().apply {
            val contentsArr = JSONArray().apply {
                val turn = JSONObject().apply {
                    val partsArr = JSONArray().apply {
                        put(JSONObject().put("text", prompt))
                    }
                    put("parts", partsArr)
                }
                put(turn)
            }
            put("contents", contentsArr)

            // Add Google Search Tool Grounding
            val toolsArr = JSONArray().apply {
                val googleSearchTool = JSONObject().apply {
                    put("googleSearch", JSONObject())
                }
                put(googleSearchTool)
            }
            put("tools", toolsArr)

            val systemInstruction = JSONObject().apply {
                val partsArr = JSONArray().apply {
                    put(JSONObject().put("text", "You are TaskPulse Android Process & Optimization Expert. Always verify background behavior, battery impact, permissions, known issues, and safety recommendations using up-to-date Google Search data. Keep your answer concise, formatted with clear bullet points, and highlight whether the app is safe to stop in background."))
                }
                put("parts", partsArr)
            }
            put("systemInstruction", systemInstruction)
        }

        try {
            val body = requestJson.toString().toRequestBody("application/json".toMediaType())
            val request = Request.Builder()
                .url(url)
                .post(body)
                .build()

            val response = client.newCall(request).execute()
            val responseBody = response.body?.string() ?: ""

            if (!response.isSuccessful) {
                return@withContext SearchGroundedResult(
                    query = prompt,
                    responseText = "Error from Gemini API: ${response.code} ${response.message}\n$responseBody",
                    errorMessage = "HTTP ${response.code}"
                )
            }

            val rootJson = JSONObject(responseBody)
            val candidates = rootJson.optJSONArray("candidates")
            if (candidates == null || candidates.length() == 0) {
                return@withContext SearchGroundedResult(
                    query = prompt,
                    responseText = "No response generated by Gemini model.",
                    errorMessage = "Empty candidates"
                )
            }

            val firstCandidate = candidates.getJSONObject(0)
            val content = firstCandidate.optJSONObject("content")
            val parts = content?.optJSONArray("parts")
            val textBuilder = StringBuilder()
            if (parts != null) {
                for (i in 0 until parts.length()) {
                    val part = parts.getJSONObject(i)
                    if (part.has("text")) {
                        textBuilder.append(part.getString("text"))
                    }
                }
            }

            // Extract Google Search Grounding Metadata
            val searchQueries = mutableListOf<String>()
            val sources = mutableListOf<GroundingChunk>()

            val groundingMetadata = firstCandidate.optJSONObject("groundingMetadata")
            if (groundingMetadata != null) {
                val queriesArr = groundingMetadata.optJSONArray("webSearchQueries")
                if (queriesArr != null) {
                    for (i in 0 until queriesArr.length()) {
                        searchQueries.add(queriesArr.getString(i))
                    }
                }

                val chunksArr = groundingMetadata.optJSONArray("groundingChunks")
                if (chunksArr != null) {
                    for (i in 0 until chunksArr.length()) {
                        val chunkObj = chunksArr.getJSONObject(i)
                        val webObj = chunkObj.optJSONObject("web")
                        if (webObj != null) {
                            val title = webObj.optString("title", "Web Source")
                            val uri = webObj.optString("uri", "")
                            if (uri.isNotBlank()) {
                                sources.add(GroundingChunk(title = title, url = uri))
                            }
                        }
                    }
                }
            }

            SearchGroundedResult(
                query = prompt,
                responseText = textBuilder.toString().ifBlank { "Analysis completed with no text output." },
                searchQueries = searchQueries,
                sources = sources.distinctBy { it.url }
            )
        } catch (e: Exception) {
            SearchGroundedResult(
                query = prompt,
                responseText = "Failed to connect to Gemini API: ${e.localizedMessage}",
                errorMessage = e.localizedMessage
            )
        }
    }
}
